# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Agent Data Types.

This module defines the core data structures used throughout the agent system.
These types provide standardized containers for actions, interaction steps,
and complete episode trajectories.
"""

from collections.abc import Hashable
import dataclasses
from enum import Enum, auto
from typing import Any, Dict, List, Optional

import numpy as np


@dataclasses.dataclass(kw_only=True)
class Action:
  """Container for structured actions that can be executed by an environment.

  The action content is environment-specific and can be any type of data
  structure (dict, string, custom object, etc.) that the target environment
  can interpret and execute.

  Attributes:
    action: The action payload, format depends on the environment.
  """

  action: Any = None


@dataclasses.dataclass(kw_only=True)
class Step:
  """Represents a single interaction step in an agent-environment conversation.

  Each Step captures the complete context of one turn: the input to the LLM,
  the model's response and reasoning, the parsed action, the environment's
  response, and associated metadata for tracking and analysis.

  Attributes:
    chat_completions: Messages sent to LLM (OpenAI Chat API format).
    thought: Agent's reasoning or chain-of-thought for this step.
    action: Parsed structured action from LLM response.
    observation: Environment's response after executing the action.
    model_response: Raw text output from the language model.
    info: Additional metadata (timestamps, debug info, trace IDs, etc.).
    reward: Immediate reward signal from environment for this step.
    done: Terminal state flag - True if episode has ended.
    mc_return: Monte Carlo return from this step to episode end.
    assistant_tokens: Token IDs generated by the assistant for this step.
    assistant_masks: Masks for assistant tokens.
    env_tokens: Token IDs generated by the environment for this step.
    env_masks: Masks for environment tokens.
    logprobs: Log probabilities for assistant tokens.
  """

  chat_completions: list[dict[str, str]] = dataclasses.field(
      default_factory=list
  )
  thought: str = ""
  action: Optional[Action] = None
  observation: Any = None
  model_response: str = ""
  info: dict[str, Any] = dataclasses.field(default_factory=dict)
  reward: float = 0.0
  done: bool = False
  mc_return: float = 0.0
  assistant_tokens: Optional[np.ndarray] = None
  assistant_masks: Optional[np.ndarray] = None
  env_tokens: Optional[np.ndarray] = None
  env_masks: Optional[np.ndarray] = None
  logprobs: Optional[np.ndarray] = None


class TrajectoryStatus(Enum):
  """Enum for trajectory status."""

  SUCCEEDED = auto()
  RUNNING = auto()

  # Agent Constraints
  MAX_STEPS_REACHED = auto()  # corresponds to `max_steps`
  MAX_CONTEXT_LIMIT_REACHED = (
      auto()
  )  # response token budget exhausted; corresponds to `max_response_length`
  TIMEOUT = auto()  # corresponds to `timeout`

  # System Errors
  ENV_TIMEOUT = auto()  # env.step hang and is killed by asyncio.wait_for
  FAILED = auto()


@dataclasses.dataclass(kw_only=True)
class Trajectory:
  """Represents a complete episode or task execution trace.

  A Trajectory contains the full sequence of Steps taken to complete a task,
  along with the task description and overall performance metrics. This is
  the primary data structure for episode storage, analysis, and replay.

  Attributes:
    task: Task description, initial prompt, or episode specification.
    steps: Chronologically ordered sequence of interaction steps.
    reward: Total episode reward (cumulative or final environment score).
    status: Status of the trajectory (e.g., "success", "truncated").
    env_time: Dictionary of environment latency metrics (reset_latency: float, step_latency: list[float] ordered by step index, close_latency: float).
  """

  task: Any = None
  steps: list[Step] = dataclasses.field(default_factory=list)
  reward: float = 0.0
  status: TrajectoryStatus = TrajectoryStatus.RUNNING
  env_time: dict[str, float] = dataclasses.field(default_factory=dict)
  reward_time: dict[str, float] = dataclasses.field(default_factory=dict)

  def to_dict(self) -> dict[str, Any]:
    """Convert trajectory to dictionary format for serialization.

    Useful for logging, storage, or transmission over APIs. All Step objects
    are recursively converted to dictionaries using dataclass serialization.

    Returns:
      dict: Serializable dictionary representation of the trajectory.
    """
    return {
        "task": self.task,
        "steps": [dataclasses.asdict(step) for step in self.steps],
        "reward": float(self.reward),
        "status": self.status.name,
        "env_time": self.env_time,
        "reward_time": self.reward_time,
    }


def format_traj_id(prompt_id: Hashable = "", group_index: int = 0) -> str:
  """Standardized trajectory identifier: traj_{prompt_id}_g{group_index}."""
  return f"traj_{prompt_id}_g{group_index}"


@dataclasses.dataclass(kw_only=True)
class TrajectoryItem:
  """Canonical trajectory container with metadata and token arrays for RL training.

  This class acts as a flexible container representing an individual rollout trajectory.
  Attribute lookups for fields not defined explicitly on the dataclass (such as
  `status`, `reward`, `prompt_tokens`, `conversation_tokens`, `conversation_masks`,
  `routed_experts`, or `policy_version`) fall back dynamically via `__getattr__` to
  `traj` (when it is a dictionary) and then to `metadata`.

  Attributes:
    prompt_id: Unique identifier for the prompt/task. Standardized across
      orchestrator and training workflows.
    group_index: Index of the rollout within its prompt group (0 .. G-1).
      Standardized across orchestrator and training workflows.
    start_step: Starting step index within the full trajectory.
    traj: The trajectory payload. Typically a dictionary in tokenized RL training
      workflows (e.g. from `TrajectoryCollectEngine(mode="Token")` containing
      `"prompt_tokens"`, `"conversation_tokens"`, `"conversation_masks"`, etc.,
      or an error dictionary), or a `Trajectory` dataclass instance when collecting
      step-by-step agent interactions (`mode="Trajectory"`) for evaluation or
      inspection.
    metadata: Arbitrary metadata dictionary for tracking, lineage, or extra parameters.
  """

  prompt_id: Hashable = ""
  group_index: int = 0
  start_step: int = 0
  traj: Any = None
  metadata: dict[str, Any] = dataclasses.field(default_factory=dict)

  def __init__(
      self,
      *,
      prompt_id: Hashable = "",
      group_index: int = 0,
      start_step: int = 0,
      traj: Any = None,
      metadata: dict[str, Any] | None = None,
      **kwargs: Any,
  ):
    self.prompt_id = prompt_id
    self.group_index = group_index
    self.start_step = start_step
    self.traj = traj
    self.metadata = dict(metadata or {})
    for k, v in kwargs.items():
      if v is not None:
        self.metadata[k] = v

  @property
  def traj_id(self) -> str:
    """Standardized trajectory identifier: traj_{prompt_id}_g{group_index}."""
    return format_traj_id(self.prompt_id, self.group_index)

  def __getattr__(self, name: str) -> Any:
    if name.startswith("__") and name.endswith("__"):
      raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    traj = self.__dict__.get("traj")
    if isinstance(traj, dict) and name in traj:
      return traj[name]
    metadata = self.__dict__.get("metadata")
    if isinstance(metadata, dict) and name in metadata:
      return metadata[name]
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

  def __getstate__(self) -> dict[str, Any]:
    return self.__dict__

  def __setstate__(self, state: dict[str, Any]) -> None:
    self.__dict__.update(state)

  def to_dict(self) -> dict[str, Any]:
    """Serializes TrajectoryItem to a dictionary."""
    traj_dict = (
        self.traj.to_dict()
        if hasattr(self.traj, "to_dict") and callable(self.traj.to_dict)
        else self.traj
    )
    return {
        "prompt_id": str(self.prompt_id),
        "group_index": int(self.group_index),
        "start_step": int(self.start_step),
        "traj": traj_dict,
        "metadata": dict(self.metadata),
    }

  @classmethod
  def from_dict(cls, data: dict[str, Any]) -> "TrajectoryItem":
    """Reconstructs TrajectoryItem from a dictionary."""
    group_index_raw = data.get("group_index", 0)
    group_index = int(group_index_raw) if group_index_raw is not None else 0
    start_step_raw = data.get("start_step", 0)
    start_step = int(start_step_raw) if start_step_raw is not None else 0
    metadata = dict(data.get("metadata", {}) or {})
    for k, v in data.items():
      if k not in (
          "prompt_id",
          "group_index",
          "start_step",
          "traj",
          "metadata",
      ):
        if k not in metadata:
          metadata[k] = v
    return cls(
        prompt_id=data.get("prompt_id", ""),
        group_index=group_index,
        start_step=start_step,
        traj=data.get("traj"),
        metadata=metadata,
    )

