# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Sampler abstractions for Distributed-RL."""

import dataclasses
from typing import Any, Protocol, Sequence, runtime_checkable
from jax import typing
import numpy as np

from tunix.experimental.common import datatypes

ArrayLike = typing.ArrayLike


@dataclasses.dataclass(kw_only=True)
class SamplingParams:
  """Engine-neutral sampling configuration for a generation request.

  Attributes:
    max_tokens: Maximum number of tokens to generate.
    temperature: Softmax temperature applied while sampling. Kept explicit so it
      can be carried through to any later log-probability scoring, ensuring the
      sampling distribution and the scoring distribution match.
    top_p: Nucleus sampling probability threshold.
    top_k: Top-k sampling candidate count threshold.
    seed: Random seed for reproducible generation.
    return_logprobs: Whether to record per-token log probabilities.
    return_logits: Whether to record per-token output logits.
    return_routed_experts: Whether to record the MoE expert ids each token was
      routed through, so training can replay them instead of re-routing. Only
      meaningful for MoE models on a backend that supports capture; the backend
      must also be configured to capture, since it is an engine-level setting.
    beam_size: Beam width for beam search decoding.
  """

  max_tokens: int = 64
  temperature: float = 1.0
  top_p: float | None = None
  top_k: int | None = None
  seed: int | None = None
  return_logprobs: bool = False
  return_logits: bool = False
  return_routed_experts: bool = False
  beam_size: int | None = None


@dataclasses.dataclass(kw_only=True)
class SamplingRequest(datatypes.Request):
  """Request to generate completions for a single prompt from a Sampler.

  Attributes:
    prompt: The source prompt to sample from (formatted string, token array, or
      chat dictionary).
    sampling_params: Optional per-request sampling configuration.
  """

  prompt: Any
  sampling_params: SamplingParams | None = None


@dataclasses.dataclass(kw_only=True)
class SamplingResponse(datatypes.Response):
  """Serializable result of a single sampling/completion request from a Sampler.

  Attributes:
    text: Detokenized completion text string generated by the model.
    prompt_token_ids: Array of prompt token IDs as tokenized by the sampler
      backend, with backend padding removed.
    token_ids: Array of generated token IDs (unpadded).
    logprobs: Array of per-token log-probabilities under the sampling policy
      (required for RL), or None if not requested.
    finish_reason: Reason generation terminated (e.g., "stop", "length",
      "cancelled", "error").
    error: Structured failure details when sampling failed for this prompt, else
      None (inherited from datatypes.Response).
    routed_experts: Per-token MoE expert ids for this one completion, shaped
      `[Length, Layers, Top K]` to match what the backend reports. Covers the
      prompt as well as the generated tokens. None if not requested, or if the
      model is dense.
  """

  text: str = ""
  prompt_token_ids: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  token_ids: np.ndarray = dataclasses.field(
      default_factory=lambda: np.zeros(0, dtype=np.int32)
  )
  logprobs: np.ndarray | None = None
  finish_reason: str = "stop"
  routed_experts: ArrayLike | None = None

  def __post_init__(self):
    if (
        self.logprobs is not None
        and self.logprobs.shape != self.token_ids.shape
    ):
      raise ValueError(
          f"logprobs shape {self.logprobs.shape} != token_ids shape"
          f" {self.token_ids.shape}"
      )


# Alias canonical DTO from datatypes module for backwards compatibility.
WeightSyncRequest = datatypes.WeightSyncRequest


@dataclasses.dataclass(kw_only=True)
class LoadInfo(datatypes.Response):
  """Load information for a Sampler."""
  num_requests_waiting: int = 0
  num_requests_running: int = 0
  kv_cache_usage_perc: float = 0.0


@runtime_checkable
class Sampler(Protocol):
  """Protocol defining standard lifecycle, sampling, and weight-sync interface for worker slices."""

  # --- Lifecycle & Topology ---
  def initialize(self) -> None:
    """Initializes backend resources before serving requests."""
    ...

  async def start(self, **kwargs) -> str | None | Any:
    """Starts the sampling server engine or local loop."""
    ...

  async def stop(self, **kwargs) -> str | None | Any:
    """Terminates sampler execution and closes local connections."""
    ...

  async def pause(self, **kwargs) -> str | None | Any:
    """Pauses inference processing on this worker slice."""
    ...

  async def resume(self, **kwargs) -> str | None | Any:
    """Resumes inference processing on this worker slice."""
    ...

  async def get_mesh(self, **kwargs) -> Any:
    """Returns the underlying device mesh topology."""
    ...

  # --- Inference ---
  async def sample(
      self,
      sampling_requests: (
          SamplingRequest
          | Sequence[SamplingRequest]
          | Any
          | Sequence[Any]
      ),
      **kwargs,
  ) -> list[SamplingResponse] | Any:
    """Generates completions for a batch of prompt conversations concurrently."""
    ...

  # --- Weight Synchronization ---
  def get_target_state(self) -> Any:
    """Returns target state shape/dtype pytree for weight conversion."""
    ...

  async def get_weight_sync_metadata(self, **kwargs) -> Any:
    """Returns the sharding specs and layout metadata across devices for policy model weights."""
    ...

  async def bind_weight_sync(
      self,
      sync_request: WeightSyncRequest | Any = None,
      **kwargs,
  ) -> Any:
    """Binds destination-side transport resources. Idempotent per round."""
    ...

  async def pre_weight_sync(
      self, sync_request: WeightSyncRequest | Any = None, **kwargs
  ) -> str | None | Any:
    """Prepares staging handshake prior to policy weight update from the specified controller."""
    ...

  async def weight_sync(
      self, sync_request: WeightSyncRequest | Any = None, **kwargs
  ) -> str | None | Any:
    """Updates model weights in-place from the specified controller."""
    ...

  async def post_weight_sync(
      self, sync_request: WeightSyncRequest | Any = None, **kwargs
  ) -> str | None | Any:
    """Finalizes and switches active policy weights after transfer completion."""
    ...

  async def abort_weight_sync(
      self, sync_request: WeightSyncRequest | Any = None, **kwargs
  ) -> str | None | Any:
    """Discards staging and restores serving the previous policy weights."""
    ...

  async def get_transfer_status(
      self, req_id: str | Any, **kwargs
  ) -> str | Any:
    """Queries the status of an ongoing weight transfer or KV-cache migration request."""
    ...

  async def migrate_kv_cache(
      self,
      source_server_id: str,
      target_server_id: str,
      token_ids: list[int],
      **kwargs,
  ) -> bool:
    """Triggers KV-cache migration from source to target slice."""
    ...

  async def get_load_info(self, **kwargs) -> LoadInfo | Any:
    """Returns the current load information for this sampler."""
    ...
